id: P010695
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17297
  title: གྲུབ་མཐའ་རྩ་བའི་ཚིག་ཊིཀ
  author: ''
  volumes:
    842c5a92bbca416da08636f4733d4c08:
      image_group_id: I8LS17308
      title: ''
      volume_number: 1
      total_pages: 116
