id: I4B45EEDB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T08:41:27+00:00'
last_modified: '2022-06-08T16:51:56.408005+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17297
  title: གྲུབ་མཐའ་རྩ་བའི་ཚིག་ཊིཀ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0BB7:
      image_group_id: I8LS17308
      title: ''
      total_pages: 116
      order: 1
      base_file: 0BB7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
